### ISSUE TITLE
How to uninstall the whole micasense package?

### ISSUE THREAD

**Issue by awake040** [micasense/imageprocessing#15]
Hi guys! There is a lot of information on how to install the environment but I can't find any information about removing. Can you give me a point in the right direction on how to remove the installed files?

Thanks a lot in advance!

**Comment by poynting** [comment]
It depends somewhat on the os and which instructions you followed, but if you installed using the instructions into a conda environment called `micasense`, open a new conda window and run 
```
conda env remove -n micasense
````
Use a new window/terminal because you need to ensure the `micasense` environment isn't active when you try to remove it.

This will remove all of the python packages installed into the `micasense` environment. You can also just delete the folder you checked out this repository into with the code and test/example images.

After that you can use the normal system uninstall methods to remove any of the installed programs like anaconda, exiftool, etc.

**Comment by awake040** [comment]
Thank you, this helps a lot already :)
