### ISSUE TITLE
test images appear to be corrupt

### ISSUE THREAD

**Issue by LummiGIS** [micasense/imageprocessing#155]
Hi, I am working through your code and see that the test images referenced in Testing image Reading and panel detection point to the image files in data/0000SET/000.
After downloading a zip of the project (on Ubuntu 20.04 an Windows10) I see that the image files appear to be corrupted.

Also, have you tested your code against Parrot Sequoia images?

**Comment by poynting** [comment]
It's likely that downloading a zip will not work due to the large size of the demo files and them being included using Git LFS.

Please follow the checkout and setup instructions (making sure to install both git and git-lfs prior to clone) and please reopen this issue if you run issues.

https://github.com/micasense/imageprocessing/issues/107

With regards to Sequoia, no, there is no support for sequoia in this code and there are no plans to add support.
