### ISSUE TITLE
Colorbar covers Image

### ISSUE THREAD

**Issue by maltepaul** [micasense/imageprocessing#22]
I have problems with the plotting tools like plotwithcolorbar. The colorbar always covers the image.
![colorbar](https://user-images.githubusercontent.com/40119184/47428100-86b4e800-d792-11e8-8eb7-ef03789c0566.png)
Not really an expert in Python so I have no idea what the problem might be.
Anyone knows how to fix this?

**Comment by poynting** [comment]
I can't recreate this, can you provide more information?

**Comment by poynting** [comment]
I'm going to close this due to lack of information and inability to reproduce on any platform. I suspect this issue has to do with incompatible versions of some of the underlying libraries, but that's just a guess.  Try using the conda installation process to create a new environment and load compatible libraries.
