### ISSUE TITLE
Applied in new dataset

### ISSUE THREAD

**Issue by SmithPeng** [micasense/imageprocessing#33]
I have your code on given sample data, and result the same as you--pixel from DN value to reflectance, and merged images have no ghosting.

Fine, and then I test code on Micasense Sample data[[website](https://www.micasense.com/rededge-mx-sample-data)], with some changes for sets of images, but results are totally not acceptable. As following image, merged rgb bands and  nir/red/green bands.
![img_0101_rgb](https://user-images.githubusercontent.com/37366612/53886401-e71a3700-405a-11e9-89c0-f014b334daa0.jpg)
![img_0101_cir](https://user-images.githubusercontent.com/37366612/53886515-26488800-405b-11e9-916d-ca9b927a7314.jpg)

The panel_reflectance_by_band are set [0.67, 0.69, 0.68, 0.61, 0.67] , isn't this problem right?

What might cause this result, I don't understand. And whether those code could apply on other fights and images of micasense camera.
@poynting

**Comment by poynting** [comment]
Of course the intention of the code is to convey concepts which can be used with any set of data. 

At a glance, it looks like pixel rollover - that the floating point reflectance values aren't being mapped into the 8-bit display range properly. Check the min/max of your reflectance compensated image and ensure that when it's mapped from float to 8-bit for display, it's mapped without rollover. For display in the alignment tutorial, the mapping is handled by running the normalize function to develop the image for display:

```
for i in range(0,im_aligned.shape[2]):
    im_display[:,:,i] =  imageutils.normalize(im_aligned[:,:,i])
```

If I use the images you're referencing, from the MicaSense website, and correct them using the same panel image as is used for the Alignment tutorial, I get a reasonable RGB image, as shown below.  The CIR/NDVI images are bad because the alignment is poor, but they don't have the problem you're describing.

The panel reflectance calibration is one thing -- but it is also necessary to determine the spectral irradiance values using an actual panel image to convert to reflectance, so you need to use a panel image taken near the same time as the image was. In this case the example data is similar enough to the tutorial irradiance conditions that it's not a problem.

![image](https://user-images.githubusercontent.com/6610131/54410440-bb293200-46a8-11e9-9020-3832d58b0a5d.png)
