### ISSUE TITLE
What is the difference between {XMP:DarkRowValue} and {EXIF:BlackLevel}?

### ISSUE THREAD

**Issue by dud3r** [micasense/imageprocessing#5]
Are these supposed to be the same? I don't understand why my {EXIF:BlackLevel} is always 4800 4800 4800 4800. From my understanding the black levels of the covered pixels should also vary from image to image. They are always the same. The {XMP:DarkRowValue} on the other hands shows different values in each image. So my guess would be that these are the correct values?

BTW: Thank you for the tutorial and code release on github. I always wanted to perform radiometric calibration myself in python, but didn't know how to approach it.

**Comment by poynting** [comment]
The DarkRowValue are the average values of the optically covered pixels; however, if you use these values your radiometric accuracy will suffer. There is processing which happens internal to the image sensor to maintain a fixed black level value at 4800, which is why `EXIF:BlackLevel` is the preferred number and should be used with the radiometric model.  

Thanks!
