### ISSUE TITLE
save a masked ndvi image as tiff file

### ISSUE THREAD

**Issue by ryu0116** [micasense/imageprocessing#76]
can i save a masked ndvi image to show it on gis?

**Comment by poynting** [comment]
Since the rendered images aren't georeferenced, I would say probably not.  See https://github.com/micasense/imageprocessing/issues/64

However, as described in that issues, it's possible to create a georeferenced map using a photogrammetry suite, and then apply the same masking in the tutorial to the map layers within the GIS.

**Comment by ryu0116** [comment]
Thank you for answering.
I will try it

**Comment by ryu0116** [comment]
I used SAGA to create a masked ndvi image and exported it to load on gis
thank you
